### ISSUE TITLE
CI stops to work

### ISSUE THREAD

**Issue by MatiasVara** [torokernel/torokernel#384]
```
travis_fold:end:dpl.1
/home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/connection.rb:19:in `get'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/client/users.rb:34:in `user'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.15/lib/dpl/provider/releases.rb:58:in `user'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.15/lib/dpl/provider/releases.rb:83:in `setup_auth'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.15/lib/dpl/provider/releases.rb:87:in `check_auth'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.15/lib/dpl/provider.rb:187:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.15/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.15/lib/dpl/provider.rb:186:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.15/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.15/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.15/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
travis_fold:start:dpl.2
```

**Comment by MatiasVara** [comment]
I am getting BAD CREDENTIAL during deployment.

**Comment by MatiasVara** [comment]
I asked the question at https://travis-ci.community/t/release-aborted-bad-credentials/1089/8

**Comment by MatiasVara** [comment]
It seems that I need to encrypt the GH_TOKEN.

**Comment by MatiasVara** [comment]
To fix this:
1. Remove the environment variable that contains the GH_TOKEN
2. Create a new personal token and encrypt it by using `travis encrypt GH_TOKEN=123444 --add` on toro repo.
3. Commit new .travis.yml and trigger build.
