### ISSUE TITLE
Networking stack drops packets when socket is full

### ISSUE THREAD

**Issue by MatiasVara** [torokernel/torokernel#468]
Vsockets support up to 16kb for the WINDOW. This means that the socket can hold up to 16kb without any reading it. If the sender sends more than the WINDOW, the networking drops those packets. This has been observed by relying on the new networking tests. There are several issues here:
1. The network stack is dropping packets without informing the user. This would require a sort of log.
2. It may be required that the user can set up how much memory the socket can hold. This may be a parameter per socket. 
3. The update-credit mechanism is not fully understood. I thought this mechanism should prevent full the receiver buffer. However, when sending a chunk of 32kb, the networking stack split it into eight 4kb-packets and full the socket's window.   

https://github.com/torokernel/torokernel/blob/f1fd0f4fe3b217b42c17411eac4b6d4e17cdf580/rtl/Network.pas#L568

**Comment by MatiasVara** [comment]
The following test is failing:
```bash
debian@d2-2-gra11:~/torokernel/fixforsprint/tests/networking$ sudo python3 ./testnetworking.py 5 80 server
Launching server test ...
Traceback (most recent call last):
  File "./testnetworking.py", line 79, in <module>
    test_server(cid, port, REQ_MAX)
  File "./testnetworking.py", line 52, in test_server
    assert msg == response, 'failed at req_len=' + str(req_len) + '-' + str(len(msg)) + '-' + str(len(response))
AssertionError: failed at req_len=32768-32768-16384
```
